version: 2.1
jobs:
  deploy:
    docker:
      - image: pionux/build-deploy:0.1
    steps:
      - run:
          name: "Deploy Backend"
          command: |
            git clone https://github.com/koompi/koompi_wifi_hotspot_backend.git
            touch deploy-backend
            echo $node > deploy-backend
            chmod +x deploy-backend && ./deploy-backend
workflows:
  workflow:
    jobs:
      - deploy